worker_processes auto;

events {
  worker_connections 1024;
}

http {
  server_tokens off;

  server {
    listen 8401;

    location / {
      proxy_http_version 1.1;
      proxy_set_header Host scan.localhost;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto http;
      proxy_pass http://nginx:4000;
    }
  }
}
